realdecoy/rdvue

template/config/app/app.scss
template/config/app/app.vue

update for application landing page, new text and layout styling

Fp 152/update index page

---

template/component/component.ts

update component.ts template file to avoid linting errors on generation

update component ts file export object syntax

---

template/config/core/package.json
template/config/env/env.dev.ts
template/config/manifest.json
template/config/services/base.ts
template/service/service.ts

- introduce axios into base project
- create base service class
- update service module to leverage base service class

service base class & axios support

---

README.md

Copy grammar in main README #12

FP-163: Update Github landing page README

---

template/component/component.ts
template/config/app/app.ts
template/config/core/package.json
template/page/page.ts

Updated the vue class imports to use newer style syntax.

#34: updated vue class imports

---

template/config/core/router.ts

The route mode was changed from hash to history

Fp 358/change route mode in template.json

---

src/modules/new/index.ts

Adjusted the output of messages logged for all optional modules

Fp 356/fix beufy and vuetify cli output

---

template/config/core/router.ts

The route name was changed from hash to history in the router.ts file

Fp 358/change route mode in router.ts file 

---

src/lib/util.ts

Updated the CLI loading animation

Animation updated

---

src/modules/new/index.ts

Fixed project and feature requests name twice

fixed project and feature requests name twice

---

src/lib/optional-modules.ts
template/config/meta/package.json
template/template.json

updated questions to show 'Choose One' or 'Choose One or More' in brackets next to the question

updated questions to show 'Choose One' or 'Choose One or More'

---

template/template.json

Auth group question changed to "[EXPERIMENTAL]" and updated the casing for the for the authentication library question.

Cosmetic changes FP-374 and FP-376

---

src/lib/optional-modules.ts
src/lib/util.ts

Revert changes made here -  https://github.com/realdecoy/rdvue/pull/92
Plugins  and feature names are now case sensitive

Fp 377 remove fp 363 case insensitivity

---

package.json
src/lib/util.ts
src/modules/new/index.ts

Loading animation has been updated to show packages, as well as a progress bar, percentage, ETA, Chunks and  Duration

FP-375/Loading animation updated

---

template/buefy/pages/buefy-sample/buefy-sample.vue
template/vuetify/manifest.json
template/vuetify/pages/vuetify-sample/vuetify-app.vue
template/vuetify/pages/vuetify-sample/vuetify-sample-component.vue

* Improved Vuetify File name
* Fixed Buefy Icon errors

made minor changes to vuetify and buefy plugins

---

README.md
src/commands/service.ts
src/lib/utilities.ts
template/service/service.ts
test/commands/generate.test.ts
test/commands/service.test.ts
test/mocha.opts

- create service command config
- update test declarations
- update service template file

add service command

---

README.md
src/commands/sm.ts
src/lib/utilities.ts
test/commands/sm.test.ts

- create store module cli config
- create test declaration
- update utilities

create store module (sm) command

---

src/commands/plugin/localization.ts

minor update to localization command file

---

src/commands/create-project/index.ts
src/commands/plugin/buefy.ts
src/commands/plugin/localization.ts
src/commands/plugin/vuetify.ts

- skip install step during preset selection
- rearrage execution order for plugins

update plugins implemetation

---

src/commands/create-project/index.ts
src/commands/plugin/buefy.ts
src/commands/plugin/localization.ts
src/commands/plugin/vuetify.ts
src/lib/constants.ts
src/lib/utilities.ts

- update template project references
- add proper check for backwards compatibility
- update console output

hotfix: update plugin implementation

---

src/commands/add/component.ts
src/commands/add/page.ts
src/commands/add/service.ts
src/commands/add/store.ts
src/lib/constants.ts

- prompt user to visit docs for clarity on how to use the module

FP-428: add documentation link to command output

---

package.json

- replace prepack script with prepublishOnly script
- important to generate /lib files for execution of cli when deployed

hotfix: Update package.json

---

package-lock.json
package.json
src/commands/plugin/buefy.ts
src/commands/plugin/localization.ts
src/commands/plugin/vuetify.ts
tsconfig.tsbuildinfo

hotfix: resolve deployment bugs

---

docs/v2/CLI-Commands.md

- https://realdecoy.atlassian.net/browse/SEPA-473
- fixed broken syntax on table
- Updated other tables with header syntax.
- Left aligned Description header column.

SEPA-473: fix broken table syntax

---

src/commands/create-project/index.ts
src/lib/constants.ts

- include step for installing design system

SEPA-497: update create-project command

---

docs/Tailwind-NativeScript.md
docs/_sidebar.md

- https://realdecoy.atlassian.net/browse/SEPA-491
- added notes for native mobile tailwind support
- added link to `_sidebar` for tailwind notes
- standardized references for native mobile to explicitly state "native mobile".

SEPA-491: Tailwind support for Native Mobile templates
